version: "3.8"

volumes:
  n8n_data:
  postgres_storage:
  ollama_storage:

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password        # users change in n8n credential later
      - POSTGRES_DB=n8n
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready","-U","root","-d","n8n"]
      interval: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:latest
    ports: ["5678:5678"]
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=root
      - DB_POSTGRESDB_PASSWORD=password
      - N8N_BASIC_AUTH_ACTIVE=false
      # allow your Chrome extension (update ID if needed)
      - N8N_API_ALLOW_ORIGIN=chrome-extension://<YOUR-EXTENSION-ID>
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - ollama_storage:/root/.ollama
